clara-parabricks/GenomeWorks

cudamapper/include/cudamapper/index.hpp
cudamapper/include/cudamapper/index_generator.hpp
cudamapper/src/index_cpu.cpp
cudamapper/src/index_cpu.hpp
cudamapper/src/index_generator_cpu.hpp
cudamapper/tests/Test_CudamapperIndexCPU.cpp
cudamapper/tests/Test_CudamapperIndexGeneratorCPU.cpp

Implementation of `IndexCPU` and tests for it
Interface of `Index` (`include/cudamapper/index.hpp`) is perhaps too specific, but for now should be good

[cudamapper] IndexCPU implementation

---

cudamapper/src/matcher.cu
cudamapper/src/matcher.hpp
cudamapper/tests/Test_CudamapperMatcher.cpp

Still not taking sketch element direction into account, i.e. if one sketch element has a certain representation in forward and the other one in reverse complement they are going to be matched

[cudamapper] Working Matcher implementation and tests

---

CMakeLists.txt
common/logging/CMakeLists.txt
cudaaligner/CMakeLists.txt
cudapoa/CMakeLists.txt

added cmake optoin to generate shared libs for
cga modules

[cga] generate shared libs

---

common/cudautils/include/cudautils/cudautils.hpp
cudaaligner/src/ukkonen_gpu.cu

Macros to guard CUDA version specific code which are easy to grep for.

[common] Added macros for CUDA version specific code

---

cudapoa/include/cudapoa/cudapoa.hpp
cudapoa/src/cudapoa_add_alignment.cu
cudapoa/src/cudapoa_batch.cpp
cudapoa/src/cudapoa_kernels.cu
cudapoa/src/cudapoa_nw_banded.cu

Adding error handling for max edge count error Issue observed in #45

[cudapoa] improve error handling in cudapoa kernels

---

ci/common/build-test-sdk.sh
ci/common/prep-init-env.sh

Update build system to use `ninja` for more readable logs

[ci] use ninja for CI builds

---

common/utils/include/claragenomics/utils/cudautils.hpp
pyclaragenomics/test/test_cudapoa_bindings.py

Added a utility to write CUDA current device neutral functions.

[common] added scoped_device_switch utility

---

cudaaligner/include/claragenomics/cudaaligner/aligner.hpp
cudaaligner/include/claragenomics/cudaaligner/alignment.hpp
cudaaligner/include/claragenomics/cudaaligner/cudaaligner.hpp
cudaaligner/src/aligner.cpp
cudaaligner/src/aligner_global.cpp
cudaaligner/src/aligner_global.hpp
cudaaligner/src/aligner_global_myers.cpp
cudaaligner/src/aligner_global_myers.hpp
cudaaligner/src/aligner_global_ukkonen.cpp
cudaaligner/src/aligner_global_ukkonen.hpp
cudaaligner/src/alignment_impl.cpp
cudaaligner/src/alignment_impl.hpp
cudaaligner/src/myers_gpu.cu
cudaaligner/src/needleman_wunsch_cpu.cpp
cudaaligner/src/ukkonen_cpu.hpp
cudaaligner/src/ukkonen_gpu.cu
cudaaligner/tests/Test_AlignerGlobal.cpp
cudaaligner/tests/Test_AlignmentImpl.cpp

Names represent operations that need to be
applied to the query sequence to obtain the target sequence.
E.g. if the query is shorter than the target, there will be insertions.

[cudaaligner] Fix meaning of insertion and deletion

---

common/utils/include/claragenomics/utils/device_buffer.cuh
cudaaligner/src/aligner_global.cpp

* [common] device_buffer added initialize() method
* [cudaaligner] AlignerGlobal: initialize device buffers

[common] add a device_memset_async for device_buffer

---

CMakeLists.txt
ci/common/build-test-sdk.sh
cudaaligner/benchmarks/README.md
cudaaligner/benchmarks/singlealignment/CMakeLists.txt
cudaaligner/benchmarks/singlebatchalignment/CMakeLists.txt
cudapoa/benchmarks/README.md
cudapoa/benchmarks/multi-batch/CMakeLists.txt
cudapoa/benchmarks/single-batch/CMakeLists.txt
cudapoa/samples/CMakeLists.txt
pyclaragenomics/setup.py

1. Updating doc version
2. Renaming benchmarks binaries

[docs] updating docs with new version

---

common/utils/include/claragenomics/utils/device_buffer.cuh

[cudamapper] merge current dev-v0.3.0 into cudamapper-dev

---

cudamapper/CMakeLists.txt
cudamapper/src/index_generator_gpu.cu
cudamapper/src/matcher.cu
cudamapper/tests/Test_CudamapperIndexGeneratorGPU.cpp

@ahehn-nv  Can you please review as you were the main author of device_buffer
@vellamike @akkamesh FYI

[cudamapper] Use device_buffer in cudamapper

---

pyclaragenomics/setup.py

Changing directory before running setup function in setup.py

---

CMakeLists.txt
cmake/CXX.cmake
common/utils/CMakeLists.txt
common/utils/include/claragenomics/utils/cudautils.hpp

Updates CGA_CU_CHECK_ERR function to abort on error
Adds optional cudaDeviceSynchronize to underlying checking function
Closes #96

[utils] updating CGA_CU_CHECK_ERR to abort

---

cudaaligner/benchmarks/singlealignment/main.cpp
cudaaligner/include/claragenomics/cudaaligner/aligner.hpp
cudaaligner/include/claragenomics/cudaaligner/alignment.hpp
cudaaligner/include/claragenomics/cudaaligner/cudaaligner.hpp
cudaaligner/src/aligner.cpp
cudaaligner/src/aligner_global.cpp
cudaaligner/src/aligner_global.hpp
cudaaligner/tests/Test_AlignerGlobal.cpp
cudaaligner/tests/Test_AlignmentImpl.cpp
pyclaragenomics/claragenomics/bindings/cudaaligner.pxd
pyclaragenomics/claragenomics/bindings/cudaaligner.pyx
pyclaragenomics/claragenomics/bindings/cudapoa.pyx
pyclaragenomics/setup.py
pyclaragenomics/test/test_cudaaligner_bindings.py
pyclaragenomics/test/test_cudapoa_bindings.py

Add python API for cudaaligner module

[pycga] adding cudaaligner python API

---

cudaaligner/CMakeLists.txt
cudaaligner/samples/CMakeLists.txt
cudaaligner/samples/sample_cudaaligner.cpp
cudapoa/samples/CMakeLists.txt
pyclaragenomics/claragenomics/bindings/cudaaligner.pyx
pyclaragenomics/samples/sample_cudaaligner
pyclaragenomics/test/test_cudaaligner_bindings.py

Adding C++ and Python API samples for cuda aligner
Closes #106

[pycga] add cuda aligner samples

---

cudamapper/include/cudamapper/index.hpp
cudamapper/src/main.cpp

* Added option to set kmer and window size via the command line
* Added help option

[cudamapper] Added command line options

---

cudamapper/CMakeLists.txt
cudamapper/include/cudamapper/overlapper.hpp
cudamapper/include/cudamapper/types.hpp
cudamapper/src/matcher.cu
cudamapper/src/matcher.hpp
cudamapper/src/overlapper_triggered.cu
cudamapper/src/overlapper_triggered.hpp

This PR includes 
- an initial port of the Overlapper module to GPU - offers ~4X speedup compared to before
Note - porting rest of the overlapper module to GPU will get rid of all the memcpy in overlapper module which is currently the top bottleneck.

[cudamapper] gpu port of overlapper module

---

cudamapper/CMakeLists.txt

install application into bin folder
remove installation of include directory

[cudamapper] install app into bin

---

cudamapper/src/matcher.cu
cudamapper/src/overlapper_triggered.cu

1. fixed overlapper thrust memory issue
2. made indexer GPU mem utilization dynamic

[cudamapper] fix overlapper memory issue

---

pyclaragenomics/samples/sample_cudapoa

Python batched poa sample drops a group when batch is full.

add dropped group after batch.reset

---

cudamapper/include/cudamapper/overlapper.hpp
cudamapper/src/cudamapper_utils.cpp
cudamapper/src/cudamapper_utils.hpp
cudamapper/src/main.cpp
cudamapper/src/overlapper.cpp
cudamapper/src/overlapper_triggered.cu
cudamapper/src/overlapper_triggered.hpp
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu

write overlaps to paf in an async thread so it does't
block the rest of the processing

[cudamapper] overlaps to paf file in async thread

---

cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh
cudamapper/tests/Test_CudamapperIndexGPU.cu

Multithreaded implementation of `IndexGPU::build_index`. This function runs on CPU and was taking a significant portion of runtime of index generation

[cudamapper] Multithreaded implementation of IndexGPU::build_index

---

pyclaragenomics/setup.py

Setting the cuda toolkit location with PyClaraGenomics

---

cudamapper/CMakeLists.txt
cudamapper/include/cudamapper/index.hpp
cudamapper/src/index.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/main.cpp
cudamapper/tests/Test_CudamapperIndexGPU.cu
cudamapper/tests/Test_CudamapperMatcher.cu

Adding fasta to fasta mapping, to check perf of reference guided assembly

[cudamapper] adding 1 fasta to another fasta mapping

---

README.md
cudamapper/include/claragenomics/cudamapper/types.hpp
cudamapper/src/overlapper.cpp

Only new change is adding cigar string format to PAF output

Merge ashg hackathon changes into dev branch

---

.clang-format
common/utils/include/claragenomics/utils/device_buffer.cuh
cudaaligner/src/aligner_global_hirschberg_myers.cpp
cudaaligner/src/aligner_global_myers.cpp
cudaaligner/src/aligner_global_ukkonen.cpp
cudaaligner/src/batched_device_matrices.cuh
cudaaligner/src/matrix_cpu.hpp
cudamapper/src/bioparser_sequence.cpp
cudamapper/src/index_gpu.cuh
cudamapper/src/minimizer.cu
cudapoa/tests/Test_CudapoaAddAlignment.cpp
cudapoa/tests/Test_CudapoaGenerateConsensus.cpp
cudapoa/tests/Test_CudapoaNW.cpp
cudapoa/tests/basic_graph.hpp
cudapoa/tests/sorted_graph.hpp

@vellamike,  please review. thanks

[common] [cudaaligner] [cudamapper] [cudapoa] Fix constructor member initializer formatting - fixes #144

---

README.md

Updating README to clarify latest release code vs development code

[README] update clone instructions

---

CMakeLists.txt
README.md
cmake/Utils.cmake

[cmake] Add an option to disable doxygen documentation generation

---

README.md
ci/common/prep-init-env.sh
ci/local/build.sh

[CI] Run CI locally

---

common/utils/CMakeLists.txt
common/utils/include/claragenomics/utils/graph.hpp
common/utils/tests/CMakeLists.txt
common/utils/tests/TestGraph.cpp
common/utils/tests/main.cpp
cudaaligner/tests/CMakeLists.txt
cudamapper/tests/CMakeLists.txt
cudapoa/include/claragenomics/cudapoa/batch.hpp
cudapoa/src/allocate_block.cpp
cudapoa/src/allocate_block.hpp
cudapoa/src/cudapoa_batch.cpp
cudapoa/src/cudapoa_batch.hpp
cudapoa/tests/CMakeLists.txt
cudapoa/tests/Test_CudapoaGenerateMSA2.cpp
cudapoa/tests/Test_CudapoaSerializeGraph.cpp

1. Adds graph class to C++ API
2. Add graph serialization to dot format
Addresses #157

[cudapoa] add graph data structure

---

pyclaragenomics/bin/evaluate_paf
pyclaragenomics/claragenomics/io/pafio.py

1. Moved script to `bin` folder
2. Added ability check against multiple overlaps within same read pair
3. Added option to skip self mapped overlaps
4. Some refactor

[evaluate_paf] Updates to PAF evaluation script

---

ci/common/build-test-sdk.sh

[CI] Use for loop insetad of find -exec to catch tests errors

---

cudamapper/include/claragenomics/cudamapper/overlapper.hpp
cudamapper/src/main.cu
cudamapper/src/overlapper_triggered.cu
cudamapper/src/overlapper_triggered.hpp
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu
cudamapper/tests/mock_index.cuh

Switching from old to new indexer and matcher.
@vellamike @ahehn-nv please review
@akkamesh @tijyojwad FYI
See #216

[cudamapper] Using new index/matcher

---

cudaaligner/src/aligner_global_hirschberg_myers.cpp
cudaaligner/src/hirschberg_myers_gpu.cu
cudaaligner/src/hirschberg_myers_gpu.cuh

An improved hotfix for issue #220. Reverting a couple of commits.

[cudaaligner] Temporary fix issue220

---

pyclaragenomics/setup.py

- Fix PyPI classifiers
- Promote version to 0.4.3
Fixes #247

[pyclaragenomics] Fix wheel liblogging linkage issue occurred in cp3.5

---

cudaaligner/CMakeLists.txt
cudaaligner/include/claragenomics/cudaaligner/alignment.hpp
cudaaligner/samples/sample_cudaaligner.cpp
cudaaligner/src/alignment.cpp
cudaaligner/src/alignment_impl.cpp
cudaaligner/src/alignment_impl.hpp
cudaaligner/tests/Test_AlignmentImpl.cpp
pyclaragenomics/claragenomics/bindings/cudaaligner.pxd
pyclaragenomics/claragenomics/bindings/cudaaligner.pyx

[cudaaligner] Added pairing string to FormattedAlignment

---

CMakeLists.txt
README.md
ci/common/prep-init-env.sh
cmake/CondaEnv.cmake

Once this goes in, we can take out this line from our custom dockerfiles - https://github.com/clara-genomics/gpuci-build-environment/blob/master/Dockerfile#L29

[env] update cmake to look at conda env when available

---

ci/common/logger.sh
ci/common/prep-init-env.sh
ci/common/test-pyclaragenomics.sh
ci/cpu/build.sh
ci/cpu/prebuild.sh
ci/gpu/build.sh
ci/gpu/prebuild.sh

Following to https://github.com/rapidsai/ops/issues/592

[CI] Activate the right conda environment in build prep script

---

README.md

Add a pointer to CUDA installation instructions

[README] add CUDA installation pointer

---

CMakeLists.txt
cudaaligner/CMakeLists.txt
cudapoa/CMakeLists.txt

This will allow building cudapoa for machines with older CPUs.

Additional flag to skip native optimized during cudapoa compilation

---

ci/checks/python-style-requirements.txt
ci/checks/style.sh

Use sphinx to generate documentation for python code

[ci] add python doc generation check

---

cudamapper/src/cudamapper_utils.hpp

`merge_n_sorted_vectors()` is not used anymore

[cudamapper] removed merge_n_sorted_vectors

---

common/utils/include/claragenomics/utils/genomeutils.hpp
cudaaligner/src/batched_device_matrices.cuh
cudaaligner/src/myers_gpu.cu
cudaaligner/tests/CMakeLists.txt
cudaaligner/tests/Test_MyersAlgorithm.cpp
cudaaligner/tests/cudaaligner_test_cases.cpp
cudaaligner/tests/cudaaligner_test_cases.hpp

* [cudaaligner] Move test cases to separate file
* [cudaaligner] Parallelize Myers internal -> full Needleman-Wunsch matrix conversion
* [common] Added generate_random_sequence function

cudaaligner test improvements

---

cudaaligner/CMakeLists.txt
cudaaligner/src/ukkonen_cpu.cpp
cudaaligner/src/ukkonen_cpu.hpp

* Moved implementation to a .cpp file
* Replaced old implementation by a naive fool-proof implementation for testing

[cudaaligner] Changes for ukkonen_cpu

---

cudamapper/include/claragenomics/cudamapper/index.hpp
cudamapper/src/index_gpu.cuh
cudamapper/tests/Test_CudamapperIndexGPU.cu

These functions will be needed for new anchors sorting

[cudamapper] Index provides helper functions for smallest and largest read_id in it

---

cmake/CUDA.cmake
common/utils/include/claragenomics/utils/cudasort.cuh
common/utils/tests/Test_GenomeUtils.cpp
cudamapper/include/claragenomics/cudamapper/index.hpp
cudamapper/include/claragenomics/cudamapper/matcher.hpp
cudamapper/src/host_cache.cu
cudamapper/src/host_cache.cuh
cudamapper/src/index.cu
cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/main.cu
cudamapper/src/matcher.cu
cudamapper/src/matcher_gpu.cu
cudamapper/src/matcher_gpu.cuh
cudamapper/src/minimizer.cu
cudamapper/src/minimizer.hpp
cudamapper/src/overlapper.cpp
cudamapper/src/overlapper_triggered.cu
cudamapper/src/overlapper_triggered.hpp
cudamapper/tests/Test_CudamapperIndexGPU.cu
cudamapper/tests/Test_CudamapperMatcherGPU.cu
cudamapper/tests/Test_CudamapperMinimizer.cpp
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu

Indexer, Matcher and Overlapper now all use (the same) custom stream. This will allow us to overlap things more easily.
@tijyojwad CIGAR (PR #307) uses its own custom stream. We should revisit this and make sure that is what we want to have
Closes #317

[cudamapper] Use custom stream

---

common/io/CMakeLists.txt
common/io/src/kseqpp_fasta_parser.cpp
common/utils/include/claragenomics/utils/buffer.hpp
common/utils/include/claragenomics/utils/device_preallocated_allocator.cuh
cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/main.cu

* [cudamapper] fixed two data races
* [common] fixed a warning in debug mode 
* [cudamapper] removed unnecessary std::move

Fixes for cudamapper

---

cudamapper/src/main.cu

As discussed in PR #370 there is no reason not to have the content of `cudamapper/src/main.cu` in namespace `claragenomics::cudamapper::`

[cudaampper] main.cu uses namespace claragenomics::cudamapper

---

cudamapper/CMakeLists.txt

Fixes cmake error due to missing DESTINATION

[cudamapper] Fix cmake failure.

---

pyclaragenomics/README.md

[pycga] Fix pyclaragenomics PyPI link

---

ci/gpu/build.sh

[CI] Enable PyPI upload in GPU jobs

---

cudamapper/include/claragenomics/cudamapper/overlapper.hpp
cudamapper/src/application_parameters.cpp
cudamapper/src/application_parameters.hpp
cudamapper/src/main.cu
cudamapper/src/overlapper.cpp
cudamapper/tests/Test_CudamapperOverlapper.cpp

This adds new logic for merging smaller overlaps into larger ones. It also optionally removes the overlaps that are merged from output.

[cudamapper] Modify fusion code to be more like minimap2

---

ci/release/pypi_uploader.sh

Pass pypi username as an argument due to https://github.com/rapidsai/ops/issues/1003

[CI] Upload to production PyPI server

---

cudapoa/benchmarks/multi_batch.hpp
cudapoa/benchmarks/single_batch.hpp
cudapoa/include/claraparabricks/genomeworks/cudapoa/utils.hpp
cudapoa/samples/sample_cudapoa.cpp
cudapoa/src/main.cpp

Fixes a bug where each read is considered a separate group in fasta input.

[cudapoa] Fixes bug with multiple fasta logic

---

ci/release/pypi_uploader.sh

Fixed in https://github.com/rapidsai/ops/issues/1003

[CI] Remove PyPI username from twine command

---

cudaaligner/include/claraparabricks/genomeworks/cudaaligner/alignment.hpp
cudaaligner/src/aligner_global.cpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/alignment_impl.cpp
cudaaligner/src/alignment_impl.hpp
cudaaligner/tests/Test_AlignerGlobal.cpp
cudaaligner/tests/Test_AlignmentImpl.cpp
cudaaligner/tests/Test_ApproximateBandedMyers.cpp

Added the methods
* Alignment::is_optimal()
* Alignment::get_edit_distance()
to the Alignment class.

[cudaaligner] alignment object extensions

---

cudaaligner/src/myers_gpu.cu
cudaaligner/tests/Test_ApproximateBandedMyers.cpp

where is_optimal() was true even though the alignment was approximate.

[cudaaligner] Extended test and fixed a bug in approximate banded Myers

---

common/base/include/claraparabricks/genomeworks/utils/cudautils.hpp
cudaaligner/benchmarks/main.cpp
cudaaligner/src/myers_gpu.cu
cudaaligner/tests/Test_MyersAlgorithm.cu
cudamapper/src/main.cu
cudamapper/tests/Test_CudamapperIndexCache.cu
cudamapper/tests/Test_CudamapperIndexGPU.cu
cudamapper/tests/Test_CudamapperMatcherGPU.cu
cudamapper/tests/Test_CudamapperMinimizer.cpp
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu
cudapoa/benchmarks/multi_batch.hpp
cudapoa/benchmarks/single_batch.hpp

[common] Introduced CudaStream an RAII class to wrap cuda streams

---

cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/minimizer.cu

Removed logging of allocation/deallocation sizes. This clutters output in debug mode and is not done anywhere else
Added and improved NVTX ranges

[cudamapper] Added NVTX ranges and removed allocation logging from IndexGPU and Matcher

---

cudaaligner/src/batched_device_matrices.cuh

Fix for an integer overflow in cudaaligner.

[cudaaligner] fixed an integer overflow

---

CMakeLists.txt
ci/common/build-test-sdk.sh
common/base/CMakeLists.txt
common/base/include/claraparabricks/genomeworks/utils/graph.hpp
common/base/src/graph.cpp
pygenomeworks/setup_pygenomeworks.py

Hotfix for #554 and experimental CUDA 11 support.

[common] Fixed a compiler warnings and a problem with CUDA 11

---

.gitmodules
CMakeLists.txt
README.md
ci/common/build-test-sdk.sh
cmake/3rdparty.cmake
cmake/BuildHTSLib.cmake
cudamapper/CMakeLists.txt
cudamapper/include/claraparabricks/genomeworks/cudamapper/utils.hpp
cudamapper/samples/sample_cudamapper.cpp
cudamapper/src/application_parameters.cpp
cudamapper/src/application_parameters.hpp
cudamapper/src/main.cu
cudamapper/src/utils.cpp

Add outputting overlapped sequences + alignments in SAM/BAM format
closes [!335](https://github.com/clara-parabricks/GenomeWorks/issues/335)

[cudamapper]: Print in SAM format

---

README.md
cudaextender/README.md
cudaextender/include/claraparabricks/genomeworks/cudaextender/utils.hpp

[cudaextender] Add and update READMEs

---

ci/common/prep-init-env.sh
ci/cpu/prebuild.sh
ci/gpu/prebuild.sh
cudaaligner/samples/sample_cudaaligner.cpp
cudaextender/samples/sample_cudaextender.cpp
cudamapper/samples/sample_cudamapper.cpp
cudapoa/samples/sample_cudapoa.cpp

Adding missing headers to sample apps to allow for compilation with gcc9.

[samples] fix sample compilation for gcc9

---

common/base/include/claraparabricks/genomeworks/utils/device_preallocated_allocator.cuh
cudapoa/benchmarks/multi_batch.hpp
cudapoa/include/claraparabricks/genomeworks/cudapoa/batch.hpp
cudapoa/samples/sample_cudapoa.cpp
cudapoa/src/allocate_block.hpp
cudapoa/src/batch.cu
cudapoa/src/cudapoa_batch.cuh
cudapoa/src/main.cpp
cudapoa/tests/Test_CudapoaSerializeGraph.cpp

- Adds DeviceAllocator as default allocator for caching device allocations.
- Updated size limit to be a int64_t everywhere.

[cudapoa] Update cudapoa to use DeviceAllocator

---

common/base/include/claraparabricks/genomeworks/utils/allocator.hpp
common/base/include/claraparabricks/genomeworks/utils/device_buffer.hpp
common/base/include/claraparabricks/genomeworks/utils/device_preallocated_allocator.cuh
common/base/include/claraparabricks/genomeworks/utils/mathutils.hpp
common/base/tests/CMakeLists.txt
common/base/tests/Test_DevicePreallocatedAllocator.cu

Closes #600
Also adds `round_up()` to `mathutils.hpp`

[common] DevicePreallocatedAllocator allocates exactly the amount of memory requested, not more

---

cudamapper/CMakeLists.txt
cudamapper/src/application_parameters.cpp
cudamapper/src/cudamapper_utils.cpp
cudamapper/src/overlapper.cpp
cudamapper/src/utils.cpp

Update missing gcc flag in cudamapper cmake and fix error resulting from missing flag

[cudamapper] add important gcc flags

---

README.md

HTSLib may require explicitly fetching automake tool to build

[docs]: Update readme to include automake for building

---

cudamapper/src/cudamapper_utils.cpp

[cudamapper] fix substr api call in kmerization function

---

README.md
cudaaligner/CMakeLists.txt
cudapoa/CMakeLists.txt

[cmake] changed compute version in cudaaligner and cudapoa to 60

---

README.md
cmake/CUDA.cmake
common/base/include/claraparabricks/genomeworks/gw_config.hpp
common/base/include/claraparabricks/genomeworks/logging/logging.hpp
cudapoa/CMakeLists.txt

also remove WARs and hacks to support CUDA 9.x
Closes #461

[sdk] update min CUDA version to 10.0

---

cudapoa/include/claraparabricks/genomeworks/cudapoa/cudapoa.hpp
cudapoa/src/cudapoa.cpp
cudapoa/src/cudapoa_batch.cuh

[cudapoa] check to ensure not all the base weights are zero

---

common/base/include/claraparabricks/genomeworks/utils/cudautils.hpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/batched_device_matrices.cuh
cudaaligner/tests/Test_MyersAlgorithm.cu
cudaextender/samples/sample_cudaextender.cpp
cudaextender/src/ungapped_xdrop.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/index_host_copy.cu
cudamapper/src/minimizer.cu
cudamapper/src/overlapper_triggered.cu
cudamapper/tests/Test_CudamapperIndexCache.cu
cudamapper/tests/Test_CudamapperIndexGPU.cu
cudamapper/tests/Test_CudamapperMatcherGPU.cu
cudamapper/tests/Test_CudamapperMinimizer.cpp
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu
cudapoa/tests/Test_CudapoaNW.cu

Renamed the asynchronous version of device_copy_n

---

cudaaligner/src/myers_gpu.cu

cudaaligner crashed with an `invalid kernel configuration` when more than 65535 alignment tasks were submitted. This PR removes the limitation (new limit 2^31-1).

[cudaaligner] Remove limitation of launching max 65535 alignments at once.

---

.gitmodules
cmake/3rdparty.cmake
common/base/include/claraparabricks/genomeworks/utils/genomeutils.hpp
cudaaligner/CMakeLists.txt
cudaaligner/src/aligner.cpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/myers_gpu.cu
cudaaligner/src/myers_gpu.cuh

* Added NVTX markers to cudaaligner
* Improved scheduling of unbalanced workloads. Larger alignments will be processed first now.
* Minor improvement of `reverse_complement()`

[cudaaaligner] Improved task scheduling for Banded Myers

---

cudaaligner/src/aligner_global_myers_banded.cpp

I forgot to implement a minor detail in this method...

[cudaaligner] Fixed bug in reset_max_bandwidth()

---

common/base/include/claraparabricks/genomeworks/utils/cudautils.hpp
common/base/include/claraparabricks/genomeworks/utils/pinned_host_vector.hpp
common/base/src/cudautils.cpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/batched_device_matrices.cuh
cudaaligner/src/cudaaligner.cpp

SDK:
* improve inlining of `gpu_assert`
* reduced frequency of `cudaSetDevice()` calls in `scoped_device_switch`
* fixed a shadow warning
cudaaligner:
* added `reserve_n_matrices()` function to batch_device_matrices
* init CUDA runtime in `cudaaligner::Init()`.

[sdk][cudaaligner] Misc. improvements

---

cudaaligner/include/claraparabricks/genomeworks/cudaaligner/aligner.hpp
cudaaligner/src/aligner_global.hpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/aligner_global_myers_banded.hpp
cudaaligner/src/alignment_impl.hpp

Added an interface to obtain pointers to the alignment results on the device.

[cudaaligner] add device results interface

---

ci/release/pypi_uploader.sh
ci/release/update-version.sh

Current month tag exists:
- minor promotion -> increase LSB by one
- patch promotion -> increase LSB by one
Current month tag does not exist:
- minor promotion -> current month versioning with 0 as LSB
- patch promotion -> Latest tag and promote LSB by one

Fix calendar versioning
