clara-parabricks/GenomeWorks

CMakeLists.txt
cmake/3rdparty.cmake
cmake/Benchmarks.cmake
cmake/CUDA.cmake
cmake/Doxygen.cmake
cmake/Tests.cmake
cudaaligner/CMakeLists.txt
cudaaligner/benchmarks/singlealignment/CMakeLists.txt
cudaaligner/benchmarks/singlebatchalignment/CMakeLists.txt
cudaaligner/tests/CMakeLists.txt
cudapoa/CMakeLists.txt
cudapoa/benchmarks/multi-batch/CMakeLists.txt
cudapoa/benchmarks/single-batch/CMakeLists.txt
cudapoa/tests/CMakeLists.txt

1. Move CUDA specific settings into its own file
2. Removed duplicate cmake min version requirements

[cmake] reorganize cmake for CUDA

---

common/utils/include/utils/genomeutils.hpp

invalid_argument is defined in stdexcept.

[common] Fix: missing include

---

.clang-format
.gitattributes
.gitmodules
CMakeLists.txt
ci/checks/check_copyright.py
ci/checks/style.sh
cudapoa/src/cudapoa_generate_msa.cu
cudapoa/tests/Test_CudapoaGenerateMSA2.cpp
cudapoa/tests/sorted_graph.hpp
pyclaragenomics/bin/assembly_evaluator
pyclaragenomics/bin/genome_simulator
pyclaragenomics/claragenomics/__init__.py
pyclaragenomics/claragenomics/io/__init__.py
pyclaragenomics/claragenomics/io/fastaio.py
pyclaragenomics/claragenomics/simulators/__init__.py
pyclaragenomics/claragenomics/simulators/genomesim.py
pyclaragenomics/claragenomics/simulators/readsim.py
pyclaragenomics/claragenomics/test/__init__.py
pyclaragenomics/claragenomics/test/test_genome_simulator.py
pyclaragenomics/claragenomics/test/test_read_simulators.py
pyclaragenomics/claragenomics/test/test_wrappers.py
pyclaragenomics/claragenomics/utilities/__init__.py
pyclaragenomics/claragenomics/utilities/utilities.py
pyclaragenomics/claragenomics/wrappers/__init__.py
pyclaragenomics/claragenomics/wrappers/wrappers.py
pyclaragenomics/requirements.txt
pyclaragenomics/setup.py

Add script to check for copyright header
Fail CI if copyright headers are missing

[ci] add check for copyright header

---

cudamapper/src/matcher.cu

Previous implementation produced correct results, but each thread processed (almost) each element in the same way

[cudamapper] Correctly increasing index in matcher's kernel

---

cudaaligner/tests/Test_AlignerGlobal.cpp
cudaaligner/tests/Test_AlignmentImpl.cpp
cudapoa/tests/Test_CudapoaBatchEnd2End.cpp

Replaced the ASSERT_STREQ/EXPECT_STREQ with ASSERT_EQ/EXPECT_EQ for std::string.
*_STREQ is only required for c-strings, where you pass a pointer but want to compare content rather than the addresses.

[common] Use gtest *_EQ on std::strings

---

cudapoa/benchmarks/multi-batch/main.cpp
cudapoa/benchmarks/multi-batch/multi_batch.hpp
cudapoa/benchmarks/single-batch/single_batch.hpp
cudapoa/include/claragenomics/cudapoa/batch.hpp
cudapoa/src/allocate_block.cpp
cudapoa/src/allocate_block.hpp
cudapoa/src/batch.cpp
cudapoa/src/cudapoa_batch.cpp
cudapoa/src/cudapoa_batch.hpp
cudapoa/tests/Test_CudapoaBatch.cpp
cudapoa/tests/Test_CudapoaBatchEnd2End.cpp
cudapoa/tests/Test_CudapoaGenerateMSA2.cpp

calculate max poas per batch based on available memory
and some temporary heuristics. heuristics currently needed
to decide how much device buffer to be used for input/output/temp
buffers and how much to use for scoring matrices.

[cudapoa] remove max poas arg from API

---

cudapoa/src/allocate_block.cpp
cudapoa/src/allocate_block.hpp
pyclaragenomics/test/test_cudapoa_bindings.py

1. Re-enable disabled cudapoa python test
2. Fix integer overflow issue in cudapoa memory management

[cudapoa] fix integer overflow

---

cudamapper/src/minimizer.cpp
cudamapper/src/minimizer.hpp
cudamapper/tests/CMakeLists.txt
cudamapper/tests/Test_CudamapperIndexCPU.cpp
cudamapper/tests/Test_CudamapperIndexGeneratorCPU.cpp
cudamapper/tests/Test_CudamapperIndexGeneratorGPU.cpp
cudamapper/tests/Test_CudamapperMinimizer.cpp

`IndexGeneratorGPU` now also uses 2-bit instead of 4-bit packing of kmer representation

[cudamapper] 2-bit packing of minimizer representation in the CPU implementation

---

cudamapper/include/cudamapper/index.hpp
cudamapper/include/cudamapper/index_generator.hpp
cudamapper/src/index_cpu.cpp
cudamapper/src/index_cpu.hpp
cudamapper/src/index_generator_cpu.cpp
cudamapper/src/index_generator_cpu.hpp
cudamapper/src/index_generator_gpu.cu
cudamapper/src/index_generator_gpu.hpp
cudamapper/src/matcher.cu
cudamapper/tests/Test_CudamapperIndexCPU.cpp
cudamapper/tests/Test_CudamapperIndexGeneratorCPU.cpp
cudamapper/tests/Test_CudamapperIndexGeneratorGPU.cpp
cudamapper/tests/Test_CudamapperMatcher.cpp

Using `std::vector` instead of `std::map` in Index<->Matcher interface.
This change has a huge performance benefit.
@akkamesh FYI

[cudamapper] Vector instead of map in Index<->Matcher interface

---

cudaaligner/src/aligner_global.cpp

Switching devices is handled by `scoped_device_switch dev(device_id_);` a few lines earlier.

[cudaaligner] fix: remove cudaSetDevice from global_aligner

---

pyclaragenomics/setup.py

Add missing rpath to address library not found issue.
Closes #127

[pycga] fixes RPATH for cmake build

---

common/utils/include/claragenomics/utils/device_buffer.cuh

Clear the CUDA runtime error in device_buffer before an out-of-memory exception is thrown.

[common] clear CUDA runtime error in device_buffer before exception is thrown

---

cudapoa/src/allocate_block.cpp
cudapoa/src/cudapoa_batch.cpp

Making `cudapoa` API device neutral
Closes #113

[cudapoa] make api functions device neutral

---

cudamapper/include/cudamapper/types.hpp
cudamapper/src/index_gpu.cuh
cudamapper/src/matcher.cu

Implicit default constructor default-initializes members of the class. This is costly when `std::vector` of that class is created, only to have new values cudaMemcpy-ed into it. In such cases no initialization is needed. This PR defines default constructor for `Anchor` which does not initilialize any member and is thus not called by the constructor.
PR also bring changes where `std::vector::shrink_to_fit()` is called to free up memory instead of `std::vector::resize(0)` which had no effect.

[cudamapper] Default constructor for Anchor

---

pyclaragenomics/setup.py

docs installation is now part of the `all` target. so if Doxygen
is available, docs will automatically installed. And not otherwise.
Explicitly calling docs target causes an error when doxygen is not installed.
Addresses #162

[pycga] remove docs installation in pycga

---

cmake/Packaging.cmake

Addresses #193 
For unrecognized platform, disable packaging.

[cmake] remove fatal error when packaging not possible

---

CMakeLists.txt

Adding subdirectories before doc generation so the right files get added to the internal doc list

[cmake] fix documentation generation for modules

---

cudamapper/include/claragenomics/cudamapper/index_two_indices.hpp
cudamapper/src/index_gpu_two_indices.cuh
cudamapper/src/index_two_indices.cu
cudamapper/tests/Test_CudamapperIndexGPUTwoIndices.cu

PR #217 added support for hashing representations in `Index`. This index extends that to `IndexTwoIndices`
Unittest only test the case when hashing is switched off. Indexer should be independent of SketchElement implementation and in the future we will replace Minimzer with a mock of SketchElement
See #221

[cudamapper] IndexTwoIndices accepts hash_representations paramater

---

cudaaligner/benchmarks/singlealignment/main.cpp
cudaaligner/src/aligner.cpp

@ohadmo found a bug in the Hirschberg-Myers implementation. This fix switches cudaaligner to use plain Myers until the bug is resolved.

[cudaaligner] Temporary hotfix on master for issue #220

---

pyclaragenomics/bin/evaluate_paf

* Fixed bug whereby if query and target were reversed in order overlaps
were not being evaluated
* Linted for PEP8 compliance
* Added printing of TP,FP and FN absolute numbers

[pyclaragenomics] `paf_eval` bugfix and lint

---

ci/local/build.sh

This script fails when used with "nvidia-container-toolkit" (recommended for GPU support)
Please refer https://github.com/NVIDIA/nvidia-docker
This change allows different 'docker run' command to start the CI
pipeline based on docker version.

[ci] nvidia-docker2 runtime is depricated since 19.3.0.

---

cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh

Generally speaking it's not necessary to do `shrink_to_fit()` after `resize()` for `thrust::device_vector`.
`resize(count)` allocates exactly `count` elements and `shrink_to_fit()` will do deallocation and allocation even it `size() == capacity()` (I started a discussion about this with Thrust developers).
We how only call `shrink_to_fit` if `capacity > size`

[cudamapper] No device shrink_to_fit in Index

---

cudamapper/include/claragenomics/cudamapper/index.hpp
cudamapper/src/index_gpu.cuh
cudamapper/src/minimizer.cu
cudamapper/src/minimizer.hpp
cudamapper/tests/Test_CudamapperIndexGPU.cu
cudamapper/tests/Test_CudamapperMinimizer.cpp

Implemented `Index::number_of_basepairs_in_longest_read()` which returns the length of the longest read in that index.
Also switched return type of `Index::number_of_reads` from `std::uint64_t` to `read_id_t`.
These methods will be needed in a future PR for Anchor sorting
See #265

[cudamapper] Get the length of the longest read

---

common/utils/include/claragenomics/utils/cudasort.cuh
common/utils/include/claragenomics/utils/mathutils.hpp
common/utils/tests/CMakeLists.txt
common/utils/tests/Test_UtilsCudasort.cu

Function takes two keys are sorts the values by both of them.
This will be needed for fast sorting of anchors.
See #265

[cga] sort_by_two_keys

---

CMakeLists.txt
common/utils/include/claragenomics/utils/allocator.hpp
common/utils/include/claragenomics/utils/buffer.hpp
common/utils/include/claragenomics/utils/cudautils.hpp
common/utils/include/claragenomics/utils/device_buffer.hpp
common/utils/include/claragenomics/utils/host_buffer.hpp
cudamapper/CMakeLists.txt
cudamapper/include/claragenomics/cudamapper/index.hpp
cudamapper/include/claragenomics/cudamapper/matcher.hpp
cudamapper/include/claragenomics/cudamapper/overlapper.hpp
cudamapper/include/claragenomics/cudamapper/types.hpp
cudamapper/src/index.cu
cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/main.cu
cudamapper/src/matcher.cu
cudamapper/src/matcher_gpu.cu
cudamapper/src/matcher_gpu.cuh
cudamapper/src/minimizer.cu
cudamapper/src/minimizer.hpp
cudamapper/src/overlapper_triggered.cu
cudamapper/src/overlapper_triggered.hpp
cudamapper/tests/Test_CudamapperIndexGPU.cu
cudamapper/tests/Test_CudamapperMatcherGPU.cu
cudamapper/tests/Test_CudamapperMinimizer.cpp
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu
cudamapper/tests/mock_index.cuh

This PR introduces the following
- Add new device_buffer/host_buffer with allocator support. 
- Use device_buffer in place of thrust::device_vector in indexer, matcher, and overlapper.
- Use cub's caching allocator to manage device_buffer allocations in cudamapper. This is optional and can be turned off during build time (helps with debugging).
- Add memory copy helper function.
Note that this PR adds device_buffer as a new module instead of replacing the existing one only to avoid any potential bugs in the pipeline outside of cudamapper. The device_buffer.hpp should eventually replace the existing device_buffer.cuh and will be used across all the modules of CGA.
Pending tasks -

[cudamapper] Cached allocator to manage device memory allocations

---

cudamapper/CMakeLists.txt
cudamapper/include/claragenomics/cudamapper/overlapper.hpp
cudamapper/src/main.cu
cudamapper/src/overlapper.cpp
cudamapper/src/overlapper_triggered.cu
cudamapper/src/overlapper_triggered.hpp
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu

- detached thread to execute filter_and_print_overlaps is launched more efficiently, as overlaps_to_add vector is passed to std::thread as a shared pointer.
- updating read names for overlap vector is moved outside of get_overlaps and now is performed on detached thread.
- filter_overlaps which takes place on CPU is slightly modified to work with overlap read_ids rather than read_names. This allows to move the omp for loop used for updating read names work on only filtered set of overlaps.

[cudamapper] Overlapper gaps

---

cudamapper/src/main.cu

host cache is used to store an index only if that index is not already cached on GPU. This should reduce RAM usage in presence of using GPU memory for caching.

improving host cache memory usage

---

cudamapper/tests/Test_CudamapperOverlapperTriggered.cu

Replaced `strcmp()` with `ASSERT_STREQ` in tests.

[cudamapper] Use ASSERT_STREQ in tests

---

common/utils/include/claragenomics/utils/allocator.hpp
common/utils/include/claragenomics/utils/cudautils.hpp
cudamapper/src/main.cu

When a new host thread is created it does not inherit `current device` from its parent, it simply gets assigned `device 0`. This can cause problems because two threads use different device/contexts.
This PR sets device in writer threads to same device as their launching worker thread.
This PR also introduces `CGA_CU_ABORT_ON_ERR`
Closes #306

[cudamapper] Call cudaSetDevice() for writer thread

---

common/utils/include/claragenomics/utils/allocator.hpp
common/utils/include/claragenomics/utils/buffer.hpp
common/utils/include/claragenomics/utils/device_preallocated_allocator.cuh

* [common] allocator added missing include + fixed unused variable warnings
* [common] buffer: avoid buffer(Allocator, cudaStream = 0) constructor for buffer(n) calls.
* [common] preallocated allocator: minor changes:
* initialize stream member of first memory block
* make create_buffer(buffer_size) use argument instead of buffer_size_ member

[common] minor fixes

---

common/utils/include/claragenomics/utils/allocator.hpp
common/utils/include/claragenomics/utils/exceptions.hpp

This PR is needed to move the cudaaligner benchmarks to new device_buffer.

[common] Added a device_memory_allocation_exception

---

cudamapper/CMakeLists.txt
cudamapper/include/claragenomics/cudamapper/index.hpp
cudamapper/src/index.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/index_host_copy.cu
cudamapper/src/index_host_copy.cuh
cudamapper/src/main.cu

`HostCache` class name is a bit misleading. `IndexHostCopy` reflects the purpose better as the object is an actual copy of an index in host memory.
I'm not completely happy with reaming base `IndexHostCopy` into `IndexHostCopyBase`, but I do feel that `IndexHostCopy` is something we should expose externally.
This PR is part of preparations for the main PR for issue #318

[cudamapper] Renamed HostCache to IndexHostCopy

---

common/io/include/claragenomics/io/fasta_parser.hpp
common/io/src/kseqpp_fasta_parser.cpp
common/io/src/kseqpp_fasta_parser.hpp
cudamapper/include/claragenomics/cudamapper/index.hpp
cudamapper/include/claragenomics/cudamapper/overlapper.hpp
cudamapper/src/index_gpu.cuh
cudamapper/src/index_host_copy.cu
cudamapper/src/index_host_copy.cuh
cudamapper/src/main.cu
cudamapper/src/overlapper.cpp
cudamapper/tests/Test_CudamapperIndexCache.cu
cudamapper/tests/Test_CudamapperIndexGPU.cu
cudamapper/tests/Test_CudamapperOverlapperTriggered.cu
cudamapper/tests/mock_fasta_parser.hpp
cudamapper/tests/mock_index.cuh

`Index` contained functions for converting `read_id` into read name and read length. This information if already available in `FastaParser` and is only used on host side when adding read names to `Overlap`s.
This also meant that a copy of `Index` had to be kept until `Overlap`s had been written to output, which is done on a separate host-only thread. This resulted in keeping two sets of indices: the one which is currently being processed and the one which has already been processed and is being written to output, which both increased memory consumption and lead to memory fragmentation.
The following functions have been removed, as well as underlying data structures:
`Index::read_id_to_read_name()`
`Index::read_id_to_read_length()`
`Index::read_ids_to_read_names()` …

[cudamapper] Removed info about reads from Index

---

cudamapper/src/overlapper.cpp

Fixed a typo which was appending characters 'em' to alignment length entry in PAF file.

Fixed a typo in `print_paf` function.

---

cudapoa/src/cudapoa_nw_banded.cu

Fixed a bug in banded NW where in some cases would throw `loop_count_exceeded_upper_bound` error code and failed to complete the alignment.
It would happen for cases where trace-back path would hit left boundary of the band.

[cudapoa] fix for Error code 8

---

cudamapper/src/index_cache.cu
cudamapper/src/index_cache.cuh

For many smaller cases (e.g. bacteria) all indices fit device memory. Currently such indices would still be copied to host. This PR introduces an option to instruct `IndexCacheHost` to skip that copy.
Part of issue #318

[cudamapper] Added skip_copy_to_host to IndexCacheHost

---

cudapoa/include/claragenomics/cudapoa/batch.hpp
cudapoa/src/allocate_block.hpp
cudapoa/src/cudapoa_batch.hpp
cudapoa/src/cudapoa_kernels.cu
cudapoa/tests/Test_CudapoaGenerateConsensus.cpp
cudapoa/tests/Test_CudapoaGenerateMSA2.cpp
pyclaragenomics/claragenomics/bindings/cudapoa.pxd
pyclaragenomics/claragenomics/bindings/cudapoa.pyx

- Changed allocation in allocate_block.hpp to infer size and type from data type. 
- Also made similar changes in cudapoa_batch.hpp. 
- Renamed typo concensus to consensus.

[cudapoa] Member type and size unification

---

pygenomeworks/test/test_cudaaligner_bindings.py

issue appears to be with how we were handling the cuda aligner tests in python. the cleanup wasn't correct, which was leading to out of order destruction in pytest. using pytest fixture ensures the objects are deleted properly after each test.
temporarily resolves intermittent bug in tests

WIP - [pygw] fix intermittent test bug

---

cudamapper/src/main.cu

`query_parser` was passed twice instead of passing both `query_parser` and `target_parser` once

[cudamapper] Passing correct parser to print_paf()

---

README.md

Combine redundant sections for build/install in the setup docs

[docs] Consolidate Build and Install sections in README

---

pygenomeworks/setup.py

Related to https://github.com/clara-parabricks/GenomeWorks/pull/488#issuecomment-655772836
Copying the correct license before setup() is executed.
Since we use `pip wheel` and not `python setup.py bdist_wheel` to create a wheel package, the entire `pygenomeworks` folder is copied to a temporary folder. Therefore, we can not rely on static symlinks/relative path.

[SDK] Copy license to pygenomeworks folder before pip executes setup()

---

cudamapper/src/main.cu

Some pairs of indices generate so much anchors that the application runs our of memory.
Application now skips such pairs and prints the number of skipped pairs so the user can decide if that number is acceptable or the application should be rerun with different parameters.
Closes #489 
Application does not print which pairs have been skipped as a PR for #490 will significantly reduce the number of overall pairs which actually get skipped. That PR will include actually printing skipped pairs of indices

[cudamapper] Skip index pair which cause OOM errors

---

cudamapper/include/claraparabricks/genomeworks/cudamapper/overlapper.hpp
cudamapper/src/main.cu
cudamapper/src/overlapper.cpp

Expose instantiation of overlapper object through a `create_overlapper()` function in the public API and replace the Overlapper creation in main.cu with public API function call.
closes #509

[cudamapper] Add create_overlapper function to instantiate overlapper object

---

common/base/include/claraparabricks/genomeworks/utils/pinned_host_vector.hpp
cudaaligner/benchmarks/main.cpp
cudaaligner/include/claraparabricks/genomeworks/cudaaligner/aligner.hpp
cudaaligner/src/aligner.cpp
cudaaligner/src/aligner_global.cpp
cudaaligner/src/aligner_global.hpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/aligner_global_myers_banded.hpp
cudaaligner/src/batched_device_matrices.cuh
cudaaligner/src/hirschberg_myers_gpu.cu
cudaaligner/src/myers_gpu.cu
cudaaligner/src/myers_gpu.cuh
cudaaligner/tests/CMakeLists.txt
cudaaligner/tests/Test_AlignerGlobal.cpp
cudaaligner/tests/Test_ApproximateBandedMyers.cpp

* Banded Myers takes an upper bound for the bandwidth now
* Banded Myers has a dynamic memory structure now - it doesn't allocate buffers of a fixed size for an alignment (based on the max_query_length and max_target_length given at construction) anymore.
* Added a new API to create a cudaaligner with a fixed bandwidth
* batched_device_matrices can accommodate matrices of different sizes now

[cudaaligner] banded myers with fixed bandwidth and low memory requirements

---

cmake/Format.cmake
cmake/GitVersion.cmake
common/base/CMakeLists.txt
common/io/CMakeLists.txt
cudaaligner/CMakeLists.txt
cudaaligner/benchmarks/CMakeLists.txt
cudaaligner/samples/CMakeLists.txt
cudamapper/CMakeLists.txt
cudamapper/samples/CMakeLists.txt
cudapoa/CMakeLists.txt
cudapoa/benchmarks/CMakeLists.txt
cudapoa/samples/CMakeLists.txt

Update cmake structure for better integration with
other tools that use GW as cmake submodule.
Keep only one project for GW, and remove "project" settings
from all modules.

[hotfix][sdk] update cmake structure

---

cudamapper/src/index_gpu.cuh

As suggested in #543 moved the call to `cudaStreamSynchronize()` for `merged_basepairs_h ` after the call to `SketchElementImpl::generate_sketch_elements()` in `IndexGPU`
Closes #543

[cudamapper] Moved cudaStreamSynchronize for merged_basepairs_h after the call to SketchElementImpl::generate_sketch_elements()

---

cudamapper/src/index_gpu.cuh
cudamapper/tests/Test_CudamapperIndexGPU.cu

`IndexGPU` was segfaulting when passed reads that are shorter than one full window (`window_size_ + kmer_size_ - 1`). This was not exposed because parser already filters out such reads, but this adds an additional level of robustness.
`IndexGPU` was making an unnecessary copy of reads in `fasta_reads` which had a measurable performance cost.

[cudamapper] IndexGPU correctly skips too short reads and does not copy basepairs twice

---

CMakeLists.txt
cudaextender/CMakeLists.txt

1. fix usage of CMAKE_SOURCE_DIR with PROJECT_SOURCE_DIR
2. make tests and benchmarks build by default

[cmake] push fixes for cmake

---

CMakeLists.txt
common/base/include/claraparabricks/genomeworks/logging/logging.hpp
cudamapper/CMakeLists.txt
cudamapper/samples/CMakeLists.txt

1. WAR fix for spdlog with gcc9. disable logging for gcc9
2. enable SAM support by default and fix cmake compile option for SAM

[logging] fix spdlog incompatibility with gcc9

---

cudaaligner/CMakeLists.txt

Inside of the cudaaligner module, cmake was setting the compile target to cudapoa instead of `${MODULE_NAME}`

[cudaaligner]: Fix cmake for cudaaligner optimization flag

---

.gitmodules
cmake/3rdparty.cmake
common/base/CMakeLists.txt
common/base/include/claraparabricks/genomeworks/logging/logging.hpp
common/base/include/claraparabricks/genomeworks/utils/allocator.hpp
common/base/include/claraparabricks/genomeworks/utils/cudautils.hpp
common/base/src/logging.cpp
cudaaligner/src/aligner_global.cpp
cudaaligner/src/aligner_global_ukkonen.cpp
cudaaligner/src/cudaaligner.cpp
cudaextender/src/cudaextender.cpp
cudamapper/CMakeLists.txt
cudamapper/src/cudamapper.cpp
cudamapper/src/index_gpu.cuh
cudamapper/src/main.cu
cudamapper/src/minimizer.cu
cudapoa/src/allocate_block.hpp
cudapoa/src/cudapoa.cpp
cudapoa/src/cudapoa_batch.cuh
pygenomeworks/setup.py

Remove spdlog as logger and replace with simple logging implementation.

[logging] remove spdlog submodule which resolves many issues

---

cudaaligner/include/claraparabricks/genomeworks/cudaaligner/alignment.hpp
cudaaligner/include/claraparabricks/genomeworks/cudaaligner/cudaaligner.hpp
cudaaligner/src/alignment_impl.cpp
cudaaligner/src/alignment_impl.hpp
cudaaligner/tests/Test_AlignmentImpl.cpp

Add support for extended CIGAR which distinguishes matches '=' and mismatches 'X'.

[cudaaligner] Add support for extended CIGAR

---

common/base/include/claraparabricks/genomeworks/utils/cudautils.hpp
cudaaligner/src/myers_gpu.cu
cudaaligner/tests/Test_HirschbergMyers.cu
cudaaligner/tests/Test_MyersAlgorithm.cu
cudaextender/src/ungapped_xdrop.cu
cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/matcher_gpu.cu
cudamapper/src/minimizer.cu

Adding error checks after all kernel calls to avoid silent errors.
This is especially important for `cudaErrorNoKernelImageForDevice` errors. Those errors happen when the kernels are launched on a GPU which does not match the architecture the code was compiled for and the runtime has cannot jit-compile the kernels due to missing or incompatible PTX code.

Add missing error checks to avoid silent errors

---

common/base/include/claraparabricks/genomeworks/utils/limits.cuh
common/base/include/claraparabricks/genomeworks/utils/pinned_host_vector.hpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/aligner_global_myers_banded.hpp
cudaaligner/src/batched_device_matrices.cuh
cudaaligner/src/myers_gpu.cu

* Make `batched_device_matrices` default-constructible.
* Add `aligner.reset_bandwidth(int32_t)` to banded Myers aligner.
Proper tests of `reset_bandwidth()` will follow in a separate PR.

[cudaaligner] Add aligner.reset_bandwidth(int32_t) to banded Myers aligner

---

common/base/include/claraparabricks/genomeworks/utils/device_buffer.hpp
cudaaligner/include/claraparabricks/genomeworks/cudaaligner/aligner.hpp
cudaaligner/src/aligner.cpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/aligner_global_myers_banded.hpp
cudaaligner/tests/Test_AlignerGlobal.cpp

* Added an abstract base class FixedBandAligner (which provides a `aligner->reset_max_bandwidth(int32_t)`).
* Renamed `aligner->reset_bandwidth(int32_t)` to `aligner->reset_max_bandwidth(int32_t)`.
* Fixed a memory-leak in device_buffer's move-assignment

[cudaaligner] Introduce FixedBandAligner interface

---

cudaaligner/src/aligner_global_hirschberg_myers.cpp

The aligner using Hirschberg-Myers overestimated the memory requirements. This resulted in less alignments being processed in parallel by the GPU than actually possible.

[cudaaligner] Corrected the memory requirements of Hirschberg-Myers

---

cudamapper/src/index_gpu.cu
cudamapper/src/index_gpu.cuh
cudamapper/src/matcher_gpu.cu

Added pragmas for ignoring `-Wunused-parameter` in Thrust.
I only added it in needed places. @ahehn-nv do you think we should simply do it everywhere where Thrust is included?

[cudamapper] Ignore -Wunused-parameter for Thrust

---

cudaaligner/include/claraparabricks/genomeworks/cudaaligner/alignment.hpp
cudaaligner/src/aligner_global_myers_banded.cpp
cudaaligner/src/alignment_impl.cpp
cudaaligner/src/alignment_impl.hpp
cudaaligner/src/myers_gpu.cu
cudaaligner/src/myers_gpu.cuh
cudaaligner/tests/Test_AlignerGlobal.cpp

* Instead of storing a flat sequence of `AlignmentType` operations, the aligner now stores a sequence of `AlignmentType` operations ("actions") and a sequence of `counts` which runlength-encode the flat sequence.
* Added functions to the `AlignmentImpl` class to store and obtain the RLE sequences and convert them to a CIGAR string. The class maintains backward compatibility for aligners that still provide the flat sequence. Those aligners need to be adapted in the future.
* banded Myers algorithm: Handle special cases, where query length and/or target length are 0.

[cudaaligner] Use RLE for alignment

---

pygenomeworks/requirements.txt

upgraded dependencies for pygenomeworks to be compatible with h5py and cupy for python3.8
Resovles #647

Update requirements for cupy and h5py
